steps:
# 1. BUILD: Build the Docker image and tag it with ':latest'.
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/clms-saas-prouduct:latest'
  - '.'

# 2. PUSH: Push the newly built container image to the Google Container Registry (GCR).
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/clms-saas-prouduct:latest'

# Explicitly list the image to push. This is critical.
images:
- 'gcr.io/$PROJECT_ID/clms-saas-prouduct:latest'