user www-data; 

server {
    # Nginx will listen on this port.
    listen 8080;
    server_name localhost;
    root /var/www/html/public;

    # Basic health check to satisfy Nginx minimum configuration
    location / {
        return 200 'OK';
    }
}