server {
    listen 8080; # Listen on 8080 as required by Cloud Run
    index index.php index.html;
    root /app/public; # Laravel's public directory

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        # FastCGI setup for PHP-FPM
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Deny access to sensitive files
    location ~ /\.env {
        deny all;
    }
}
